# Generated by Django 3.1.7 on 2021-03-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailHoneyPotSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.TextField(blank=True, help_text='Ex: spammers.com, one per line please', verbose_name='Blocked by domains')),
                ('keywords', models.TextField(blank=True, help_text='Separate each keyword with comma or new line', verbose_name='Keywords')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
